export const articles = [
  {
    title: "article one",
    content:
      "article one content\naaaa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa",
    tags: ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6"],
    key: "1",
  },
  {
    title: "article two",
    content: "article two content",
    tags: ["tag1", "tag2", "tag3"],
    key: "2",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "3",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "4",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "5",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "6",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "7",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "8",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "9",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "10",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "11",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "12",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "13",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "14",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "15",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "16",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "17",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "18",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "19",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "20",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "21",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "22",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "23",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "24",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "25",
  },
  {
    title: "article three",
    content: "article three content",
    tags: ["tag1", "tag2", "tag3"],
    key: "26",
  },
];
