export const articles = [
  {
    title: "article 1",
    content:
      "article 1 content\naaaa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa\naa",
    tags: ["tag1", "tag2", "tag3", "tag4", "tag5", "tag6"],
    key: "1",
  },
  {
    title: "article 2",
    content: "article 2 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "2",
  },
  {
    title: "article 3",
    content: "article 3 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "3",
  },
  {
    title: "article 4",
    content: "article 4 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "4",
  },
  {
    title: "article 5",
    content: "article 5 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "5",
  },
  {
    title: "article 6",
    content: "article 6 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "6",
  },
  {
    title: "article 7",
    content: "article 7 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "7",
  },
  {
    title: "article 8",
    content: "article 8 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "8",
  },
  {
    title: "article 9",
    content: "article 9 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "9",
  },
  {
    title: "article 10",
    content: "article 10 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "10",
  },
  {
    title: "article 11",
    content: "article 11 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "11",
  },
  {
    title: "article 12",
    content: "article 12 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "12",
  },
  {
    title: "article 13",
    content: "article 13 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "13",
  },
  {
    title: "article 14",
    content: "article 14 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "14",
  },
  {
    title: "article 15",
    content: "article 15 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "15",
  },
  {
    title: "article 16",
    content: "article 16 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "16",
  },
  {
    title: "article 17",
    content: "article 17 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "17",
  },
  {
    title: "article 18",
    content: "article 18 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "18",
  },
  {
    title: "article 19",
    content: "article 19 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "19",
  },
  {
    title: "article 20",
    content: "article 20 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "20",
  },
  {
    title: "article 21",
    content: "article 21 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "21",
  },
  {
    title: "article 22",
    content: "article 22 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "22",
  },
  {
    title: "article 23",
    content: "article 23 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "23",
  },
  {
    title: "article 24",
    content: "article 24 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "24",
  },
  {
    title: "article 25",
    content: "article 25 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "25",
  },
  {
    title: "article 26",
    content: "article 26 content",
    tags: ["tag1", "tag2", "tag3"],
    key: "26",
  },
];
